language: python
python:
    - "3.4"
install: "pip install -r requirements.txt"
script:
    - "flake8"
    - "python manage.py test"
notifications:
    email:
        on_failure:
            - "kiraarik@sibmail.com"
